### ISSUE TITLE
Installation Error in HA

### ISSUE THREAD

**Issue by helson22** [dixi83/hassio-addons#25]
Hi there!

I get an installation error in HomeAsstistant latest Version (installed yesterday). Please view attached screenshot.
![Screenshot_20240922-213020_Home Assistant](https://github.com/user-attachments/assets/11994f6a-68d2-4a41-8ae0-3a5c658088b0)

Please help.

BR

**Comment by dixi83** [comment]
Broken package... It is fixed now. You might need to force a rebuild.

I need to find out how to automate this.

**Comment by helson22** [comment]
Hi again, thank you for fixing. I made a rebuild.
After starting the service light is green, change to another page in HA and return to the service/addon page it shows a red light in the upper right corner.
I have to start again, loop... 

Add-on version: 1.0.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.9.2
 Home Assistant Supervisor: 2024.09.1

Log shows an error. Maybe the problem is that my HA installation has no config folder but /homeassistant. Can this be the cause? 

`throw new Error(msg);
		^

Error: Config file '/config/config.yaml' not found
    at Object.error (/usr/src/mqtt-s7-connector/service_functions.js:57:9)
    at Object.config (/usr/src/mqtt-s7-connector/config_handler.js:40:20)
    at Object.<anonymous> (/usr/src/mqtt-s7-connector/index.js:11:29)
    at Module._compile `



BR

**Comment by dixi83** [comment]
This is noted in the documentation.... https://github.com/dixi83/hassio-addons/blob/main/mqtt-s7-connector/DOCS.md#addon-options
If anything is missing/unclear here then let me know.

**Comment by helson22** [comment]
Hi,

thank you fo your hint.

I have not /config folder. instead my home folder in HA File Explorer ist /homeassistant.

So I created the path you suggested - with the host id:
/homeassistant/addon_configs/50fb1dfd-mqtt-s7-connector/config.yam


The Add-ONe thinks now the config is in /**config**/homeassistant/addon_configs/50fb1dfd-mqtt-s7-connector/config.yaml

I can't go one level higher than /homeassistant in file explorer.

`Add-on version: 1.0.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.9.2
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to WARNING
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init: starting
s6-rc: info: service init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

> s7-mqtt-connector@1.0.4 start
> node index.js --addonversion 1.0.6 --config /config/homeassistant/addon_configs/50fb1dfd-mqtt-s7-connector/config.yaml --loglevel=4

## INIT   ## log level is set to: 4
2024-9-24 21:1:52 ## ERROR  ## Config file '/config/homeassistant/addon_configs/50fb1dfd-mqtt-s7-connector/config.yaml' not found
/usr/src/mqtt-s7-connector/service_functions.js:57
		throw new Error(msg);
		^`

BTW: the update button in the log Tab doesn't work I think(?)

**Comment by dixi83** [comment]
you are thinking to complicated I think... ;)

The `/config` folder is inside the add-on container... not on your home assistant machine.

Just 6 simple steps:
1. install the add-on,
2. run it once,
3. access the `/addon_configs/xxxxxxxx_mqtt-s7-connector` folder which is created. Using one of the suggestions in the documentation. Easiest suggestion for you is using the "file editor" add-on
4. copy the example file and rename it to `config.yaml`
5. Try running it again (it will fail because the pre-configured PLC will have a different IP than yours)
6. Edit the `config.yaml` file with the "file editor" add-on and configure it to your needs and try again.

The update button is outside my scope. But if the add-on fails, it stops and there is nothing left to show.

**Comment by helson22** [comment]
Ok now I got a PLC connected - sorry not to reply earlier. Thank you!
