### ISSUE TITLE
Config Path

### ISSUE THREAD

**Issue by helson22** [dixi83/hassio-addons#45]
Hello,

the default config directory is `/addon_configs\xxxxxxxx_mqtt-s7-connector` as mentioned in the docs.

I tried to relocated the config.yaml like this > `/config/S7_connector/config_plc1.yaml` and this in the add-on config tab page

`config_files: - /config/S7-connector/config_HCPU1.yaml`

all above produces this log entry:

`> node index.js --addonversion 1.0.6 --config /config//config/S7-connector/config_HCPU1.yaml --loglevel=4`

Ok config folder displayed twice with a slash too much... config corrected to >
`config_files:  - S7_connector/config_plc1.yaml`

then got 
`> node index.js --addonversion 1.0.6 --config /config/S7_connector/config_plc1.yaml --loglevel=4`

Is it possible to move those config files to /config folder?

**Comment by dixi83** [comment]
This is the way the [Home Assistant - addon system](https://developers.home-assistant.io/blog/2023/11/06/public-addon-config?_highlight=addon_config#new-addon_configs-folder) is designed. I personally want to stick with this. And I don't see a reason to work around this.

**Comment by helson22** [comment]
Ok just asked :-)

Then I stick to VScode with the addon_config folder added to the vscode workspace to edit the config yamls.

Thank you.
